In [1]:
def subset1(array,num):

    if num == 0 or num < 1:
        return None
    elif len(array) == 0:
        return None
    else:
        if abs(array[0] - num )< 0.001 :#        if array[0] == num:
            return [array[0]]
        else:
            with_v = subset1(array[1:],(num - array[0])) 
            if with_v:
                return [array[0]] + with_v
            else:
                return subset1(array[1:],num)

In [23]:
import numpy as np 
import pandas as pd
from pandas import Series,DataFrame
from numpy import random,mat
data = pd.read_excel('./15.xlsx',header=None) # 读取文件路径
data = data.values
Mlen = len(np.unique([i for j in data for i in j]))
#Mlen = len(np.unique(data))
#M=np.zeros((Mlen,Mlen),dtype=float)#行列数是所有节点的个数
#print(Mlen)
Max = data.max()+1
M=np.zeros((Max,Max),dtype=float)#行列数是所有节点的个数
print(Max)

u=0
p=0.02
noise = []
parent1 = []
child = []
Input_one = []
Input_two = []

for j in range(1):
    n = np.random.normal(u,p,M.shape[1])#n = np.random.normal(u,p,10)
    c = np.random.randint(25, size=M.shape[1])#uniform,randint
    input_one = n + c
    input_one = input_one.tolist()
    input_two = input_one.copy()
    Input_one.append(input_one)
    Input_two.append(input_two)
    for i in data:
        print(i)
        node_a = i[1]
        node_b = i[0]
        print(node_a)
        print(node_b)
        M[node_a][node_b]=1
        M[node_b][node_a]=1
        A = input_one[node_a] + input_one[node_b]
        input_one[node_b] = A
        parent1.append(A)
        input_three = input_two + input_one
    child.append(input_three)
print(M)

93
[0 1]
1
0
[0 2]
2
0
[0 3]
3
0
[2 4]
4
2
[2 5]
5
2
[5 6]
6
5
[3 7]
7
3
[7 8]
8
7
[7 9]
9
7
[ 7 10]
10
7
[ 9 11]
11
9
[10 12]
12
10
[10 13]
13
10
[11 14]
14
11
[11 15]
15
11
[16 17]
17
16
[16 18]
18
16
[13 19]
19
13
[13 20]
20
13
[19 21]
21
19
[20 22]
22
20
[20 23]
23
20
[23 24]
24
23
[23 25]
25
23
[25 26]
26
25
[25 27]
27
25
[26 28]
28
26
[26 29]
29
26
[28 30]
30
28
[27 31]
31
27
[31 32]
32
31
[32 33]
33
32
[29 34]
34
29
[12 16]
16
12
[35 36]
36
35
[35 37]
37
35
[36 38]
38
36
[36 39]
39
36
[39 40]
40
39
[37 41]
41
37
[37 42]
42
37
[42 43]
43
42
[42 44]
44
42
[44 45]
45
44
[44 46]
46
44
[45 47]
47
45
[46 48]
48
46
[46 49]
49
46
[49 50]
50
49
[50 51]
51
50
[52 53]
53
52
[53 54]
54
53
[54 55]
55
54
[54 56]
56
54
[55 57]
57
55
[56 58]
58
56
[56 59]
59
56
[58 60]
60
58
[59 61]
61
59
[59 62]
62
59
[62 64]
64
62
[64 65]
65
64
[65 64]
64
65
[65 66]
66
65
[67 68]
68
67
[67 69]
69
67
[67 70]
70
67
[68 71]
71
68
[71 72]
72
71
[72 73]
73
72
[69 74]
74
69
[69 75]
75
69
[74 76]
76
74
[76 77]
77
76

In [24]:
#parent = [parent1[i:i + len(data)] for i in range(0, len(parent1), len(data))]
nested_i = child
nested_d = Input_one
leni=len(child[0])
#lend=len(parent[0])
nested_d1=[i for j in nested_d for i in j]
nested_i1=[i for j in nested_d for i in j]


In [25]:
parent = []
for n in range(len(Input_one)):
    A = [x for x in Input_one[n] if x not in Input_two[n]]
    parent.append(A)

lend=len(parent[0])
lend

58

In [26]:
from collections import Counter
from statistics import mode
from operator import itemgetter
import itertools
result_dic={}
lst1=[]
lst2=[]
Index=[]
subset_list1=[]
x1 = -1
for t in nested_d:
    x = 0
    x1 = x1+1
    for num in parent[x]:
        num = parent[x1][x]
        print(nested_d[x1].index(num,x))
        x = x+1
        y = 0
        subset_list = []
        for i in nested_i[x1]:
            newnums=[i for i in nested_i[x1] if i<num]
            a=subset1(newnums[y:],num)#克服动态规划只能输出第一个匹配的结果，每次遍历完子列表后将第一个数据删除
            lst1.append(a)
            y=y+1
            list.clear(Index)
            list.clear(lst2)
            if a != None:   
                for n in a:
                    if a in Input_one[x1]:
                        A=[i for i,x in enumerate(Input_one[x1]) if x==n]#获取子节点的index，但是由于同一个数字可能有多个index
                    else:
                        A=[i for i,x in enumerate(Input_two[x1]) if x==n]#获取子节点的index，但是由于同一个数字可能有多个index
                    Index.append(A)
                B=Index
                C=list(itertools.product(*B))#所以把所有index排列组合得到结果            
            lst2.append(C)
            result_dic.clear()
            for item_str in lst2:
                for m in item_str:
                    if m not in result_dic:
                        result_dic[m]=1
                    else:
                        result_dic[m]+=1#新建一个字典，对子节点index合集投票
                        values_list = list(result_dic.values())
                counts = Counter(result_dic)
                maxcount = [value for value, count in counts.most_common()]
                subset_list.append(maxcount)
        subset_list1.append(subset_list)
            
        

0
2
3
5
7
9
10
11
12
13
16
19
20
23
25
26
27
28
29
31
32
35
36
37
39
42
44
45
46
49
50
52
53
54
55
56
58
59
62
64
65
67
68
69
71
72
74
75
76
78
79
80
82
83
84
85
88
90


In [35]:
#import random
#random.shuffle(parent[0])

In [36]:

m = np.zeros((Max,Max),dtype=float)#创建验证用空列表
row=[]
fin=[]
fin1=[]
x=0
for i in parent[0]:   
    #i = parent[x]
    dindex1 = nested_d[0].index(i)#获取父节点的index，为了便于验证，加上子节点的数量)
    A=subset_list1[x::lend]#根据父节点的个数隔位取对应的子集
    x=x+1
    list.clear(fin)
    print(dindex1)
    for i in A:
        for j in i:
            for s in j:
                fin.append(j)
                maxlabel = max(fin,key=fin.count)
                maxlabel1=[i for j in maxlabel for i in j]
    for item in maxlabel1:
        if item != dindex1:
            if m[:,item].any()== 0:
                row.clear()
                row.append(item)
                print(row)
                m[dindex1][row]=1


0
[15]
[17]
[18]
[48]
2
[33]
[51]
[57]
[86]
[92]
3
[81]
5
[47]
[91]
7
[77]
[87]
9
[63]
[89]
10
[6]
[14]
[30]
11
[43]
[66]
12
[24]
[40]
13
[8]
16
[34]
19
20
[0]
[1]
[2]
[3]
[52]
[83]
[85]
23
[90]
25
26
[21]
27
28
29
31
[58]
[65]
[74]
32
35
[60]
[73]
36
37
[7]
39
42
44
45
46
49
50
[82]
52
53
54
55
56
58
59
62
64
[22]
65
67
[26]
[68]
[72]
68
69
71
72
74
75
76
78
79
80
82
83
[61]
84
85
88
90


In [37]:
m

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
mt=m.T
m=m+mt
m

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [39]:
M

array([[0., 1., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [40]:
flatten_arr1 = np.ravel(M)
flatten_arr2 = np.ravel(m)

print (flatten_arr1)
print (flatten_arr2)#将两个矩阵平铺

[0. 1. 1. ... 1. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]


In [41]:
test = np.equal(flatten_arr1,flatten_arr2)
count1 = sum(test[test == True])#两个矩阵相同数据的个数
H=m.shape[0]
L=m.shape[1]
R=H*L#矩阵的长×宽=矩阵数据数量
accuracy=count1/R
accuracy#准确率：相同数据的个数/原有数据数量

0.9694762400277489